spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:AWU20181023/config-repo.git
          username: AWU20181023
          password: *********
          basedir: D:/ideaproject/config-repo/basedir
eureka:
  client:
    service-url:
      defaultZone: http://172.16.227.128:8761/eureka/
server:
  port: 8082
